import '../entities/coverage_data.dart';
import '../entities/html_report_options.dart';
import '../entities/line_coverage.dart';
import '../entities/source_file.dart';
import '../../generators/css_generator.dart';
import '../../utils/coverage_calculator.dart';

/// Pure use case that renders a [CoverageData] into HTML report pages.
///
/// Rendering is a *total* function of already-parsed data: it cannot fail, so
/// it returns the pages directly (a `Map` from report-relative path to HTML)
/// rather than an `Either`. Writing the pages to disk is the fallible part and
/// lives in `HtmlReportDatasource`. This class never throws and never touches
/// the file system.
///
/// The returned map always contains `index.html` plus one page per source file,
/// named by flattening the source path (separators replaced with `_`).
class GenerateHtmlReportUseCase {
  /// Creates the HTML report use case.
  const GenerateHtmlReportUseCase();

  /// Renders [coverageData] into a map of `index.html` and per-file pages.
  Map<String, String> call(
    CoverageData coverageData, {
    HtmlReportOptions options = const HtmlReportOptions(),
  }) {
    final pages = <String, String>{
      'index.html': _indexHtml(coverageData, options),
    };

    for (final sourceFile in coverageData.sourceFiles) {
      final name = sourceFileName(sourceFile.path);
      pages[name] = _sourceFileHtml(sourceFile, coverageData, options);
    }

    return pages;
  }

  /// The report-relative HTML file name for a source file [path].
  String sourceFileName(String path) =>
      '${path.replaceAll('/', '_').replaceAll('\\', '_')}.html';

  String _indexHtml(CoverageData data, HtmlReportOptions options) {
    final timestamp = _formatTimestamp(data.timestamp);
    final sortedFiles = _sortSourceFiles(data.sourceFiles);

    return '''<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>${_escapeHtml(options.title)}</title>
    ${CssGenerator.generateInlineCss()}
</head>
<body>
    <div class="header">
        <h1>${_escapeHtml(options.title)}</h1>
        <p>Generated on: $timestamp</p>
    </div>
    
    <div class="summary">
        <h2>Summary</h2>
        ${_summaryTable(data, options)}
    </div>
    
    <div class="files">
        <h2>Files</h2>
        ${_fileListTable(sortedFiles, options)}
    </div>
    
    <div class="footer">
        Generated by genhtml
    </div>
</body>
</html>''';
  }

  String _sourceFileHtml(
    SourceFile sourceFile,
    CoverageData data,
    HtmlReportOptions options,
  ) {
    final timestamp = _formatTimestamp(data.timestamp);
    final breadcrumb = _breadcrumb(sourceFile.path);
    final sourceCode = _sourceCode(sourceFile);

    return '''<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>${_escapeHtml(sourceFile.path)} - ${_escapeHtml(options.title)}</title>
    ${CssGenerator.generateInlineCss()}
</head>
<body>
    <div class="header">
        <h1>${_escapeHtml(options.title)}</h1>
        <p>Generated on: $timestamp</p>
    </div>
    
    $breadcrumb
    
    <div class="summary">
        <h2>File: ${_escapeHtml(sourceFile.path)}</h2>
        ${_fileSummaryTable(sourceFile, options)}
    </div>
    
    <div class="source-code">
        $sourceCode
    </div>
    
    <div class="footer">
        Generated by genhtml
    </div>
</body>
</html>''';
  }

  String _summaryTable(CoverageData data, HtmlReportOptions options) {
    final summary = data.summary;
    return '''<table class="coverage-table">
            <tr>
                <th>Metric</th>
                <th>Coverage</th>
                <th>Functions</th>
                <th>Lines</th>
                ${options.showBranches ? '<th>Branches</th>' : ''}
            </tr>
            <tr>
                <td>Total</td>
                <td class="${CssGenerator.getCoverageClass(summary.overallCoveragePercentage)}">${CoverageCalculator.formatCoveragePercentage(summary.overallCoveragePercentage)}</td>
                <td>${summary.functionsCoverageString}</td>
                <td>${summary.linesCoverageString}</td>
                ${options.showBranches ? '<td>${summary.branchesCoverageString}</td>' : ''}
            </tr>
        </table>''';
  }

  String _fileListTable(
    List<SourceFile> sourceFiles,
    HtmlReportOptions options,
  ) {
    final buffer = StringBuffer();

    buffer.writeln('<table class="coverage-table">');
    buffer.writeln('    <tr>');
    buffer.writeln('        <th>File</th>');
    buffer.writeln('        <th>Line Coverage</th>');
    if (options.showFunctions) {
      buffer.writeln('        <th>Function Coverage</th>');
    }
    if (options.showBranches) {
      buffer.writeln('        <th>Branch Coverage</th>');
    }
    buffer.writeln('        <th>Lines</th>');
    if (options.showFunctions) {
      buffer.writeln('        <th>Functions</th>');
    }
    if (options.showBranches) {
      buffer.writeln('        <th>Branches</th>');
    }
    buffer.writeln('    </tr>');

    for (final sourceFile in sourceFiles) {
      buffer.writeln('    <tr>');
      buffer.writeln(
        '        <td><a href="${sourceFileName(sourceFile.path)}" class="file-link">${_escapeHtml(sourceFile.path)}</a></td>',
      );
      buffer.writeln(
        '        <td class="${CssGenerator.getCoverageClass(sourceFile.lineCoveragePercentage)}">${CoverageCalculator.formatCoveragePercentage(sourceFile.lineCoveragePercentage)}</td>',
      );

      if (options.showFunctions) {
        buffer.writeln(
          '        <td class="${CssGenerator.getCoverageClass(sourceFile.functionCoveragePercentage)}">${CoverageCalculator.formatCoveragePercentage(sourceFile.functionCoveragePercentage)}</td>',
        );
      }

      if (options.showBranches) {
        buffer.writeln(
          '        <td class="${CssGenerator.getCoverageClass(sourceFile.branchCoveragePercentage)}">${CoverageCalculator.formatCoveragePercentage(sourceFile.branchCoveragePercentage)}</td>',
        );
      }

      buffer.writeln(
        '        <td>${sourceFile.hitLines}/${sourceFile.totalLines}</td>',
      );

      if (options.showFunctions) {
        buffer.writeln(
          '        <td>${sourceFile.hitFunctions}/${sourceFile.totalFunctions}</td>',
        );
      }

      if (options.showBranches) {
        buffer.writeln(
          '        <td>${sourceFile.hitBranches}/${sourceFile.totalBranches}</td>',
        );
      }

      buffer.writeln('    </tr>');
    }

    buffer.writeln('</table>');
    return buffer.toString();
  }

  String _fileSummaryTable(SourceFile sourceFile, HtmlReportOptions options) {
    return '''<table class="coverage-table">
            <tr>
                <th>Metric</th>
                <th>Coverage</th>
                <th>Total</th>
                <th>Covered</th>
            </tr>
            <tr>
                <td>Lines</td>
                <td class="${CssGenerator.getCoverageClass(sourceFile.lineCoveragePercentage)}">${CoverageCalculator.formatCoveragePercentage(sourceFile.lineCoveragePercentage)}</td>
                <td>${sourceFile.totalLines}</td>
                <td>${sourceFile.hitLines}</td>
            </tr>
            ${options.showFunctions ? '''<tr>
                <td>Functions</td>
                <td class="${CssGenerator.getCoverageClass(sourceFile.functionCoveragePercentage)}">${CoverageCalculator.formatCoveragePercentage(sourceFile.functionCoveragePercentage)}</td>
                <td>${sourceFile.totalFunctions}</td>
                <td>${sourceFile.hitFunctions}</td>
            </tr>''' : ''}
            ${options.showBranches ? '''<tr>
                <td>Branches</td>
                <td class="${CssGenerator.getCoverageClass(sourceFile.branchCoveragePercentage)}">${CoverageCalculator.formatCoveragePercentage(sourceFile.branchCoveragePercentage)}</td>
                <td>${sourceFile.totalBranches}</td>
                <td>${sourceFile.hitBranches}</td>
            </tr>''' : ''}
        </table>''';
  }

  String _breadcrumb(String filePath) {
    final parts = filePath.split('/');
    final buffer = StringBuffer();

    buffer.writeln('<div class="breadcrumb">');
    buffer.write('<a href="index.html">Coverage Report</a>');

    for (final part in parts) {
      buffer.write('<span class="separator">»</span>');
      buffer.write('<span>${_escapeHtml(part)}</span>');
    }

    buffer.writeln('</div>');
    return buffer.toString();
  }

  String _sourceCode(SourceFile sourceFile) {
    final buffer = StringBuffer();

    final lineCoverageMap = <int, LineCoverage>{};
    for (final line in sourceFile.lines) {
      lineCoverageMap[line.lineNumber] = line;
    }

    final maxLineNumber = sourceFile.lines.isEmpty
        ? 0
        : sourceFile.lines
              .map((l) => l.lineNumber)
              .reduce((a, b) => a > b ? a : b);

    for (var lineNum = 1; lineNum <= maxLineNumber; lineNum++) {
      final coverage = lineCoverageMap[lineNum];
      final cssClass = coverage != null
          ? CssGenerator.getLineCoverageClass(coverage.hitCount)
          : 'line-no-code';

      final hitDisplay = coverage != null ? coverage.hitCount.toString() : '';

      buffer.writeln('        <div class="source-line $cssClass">');
      buffer.writeln('            <div class="line-number">$lineNum</div>');
      buffer.writeln('            <div class="line-hits">$hitDisplay</div>');
      buffer.writeln(
        '            <div class="line-content">// Source code line $lineNum</div>',
      );
      buffer.writeln('        </div>');
    }

    return buffer.toString();
  }

  List<SourceFile> _sortSourceFiles(List<SourceFile> sourceFiles) {
    final files = List<SourceFile>.from(sourceFiles);
    files.sort((a, b) {
      final coverageComparison = a.overallCoveragePercentage.compareTo(
        b.overallCoveragePercentage,
      );
      if (coverageComparison != 0) return coverageComparison;
      return a.path.compareTo(b.path);
    });
    return files;
  }

  String _formatTimestamp(DateTime timestamp) =>
      timestamp.toIso8601String().replaceAll('T', ' ').substring(0, 19);

  String _escapeHtml(String text) {
    return text
        .replaceAll('&', '&amp;')
        .replaceAll('<', '&lt;')
        .replaceAll('>', '&gt;')
        .replaceAll('"', '&quot;')
        .replaceAll("'", '&#x27;');
  }
}
