name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Dart SDK
      uses: dart-lang/setup-dart@v1
      with:
        sdk: '3.9.2'
    
    - name: Install dependencies
      run: dart pub get
    
    - name: Run tests
      run: dart test
    
    - name: Run linting
      run: dart analyze

  build-test:
    name: Build Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    needs: test
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Dart SDK
      uses: dart-lang/setup-dart@v1
      with:
        sdk: '3.9.2'
    
    - name: Install dependencies
      run: dart pub get
    
    - name: Build executable
      run: |
        if [[ "${{ runner.os }}" == "Windows" ]]; then
          dart compile exe bin/genhtml.dart -o genhtml-test.exe
        else
          dart compile exe bin/genhtml.dart -o genhtml-test
        fi
      shell: bash
    
    - name: Verify executable works
      run: |
        if [[ "${{ runner.os }}" == "Windows" ]]; then
          ./genhtml-test.exe --help
        else
          chmod +x genhtml-test
          ./genhtml-test --help
        fi
      shell: bash